# Generated by Django 5.2.1 on 2025-06-20 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_number', models.IntegerField(primary_key=True, serialize=False)),
                ('coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('company', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryManager',
            fields=[
                ('inventory_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], max_length=10, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specialization_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('receptionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('spare_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_in_stock', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('test_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleComponent',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicSchedule',
            fields=[
                ('mechanic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vmsms.mechanic')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('normal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=45, null=True)),
                ('test_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('component_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('license_plate', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vin_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vmsms.customer')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vmsms.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_code', models.CharField(max_length=45)),
                ('repair_name', models.CharField(blank=True, max_length=120, null=True)),
                ('repair_date', models.DateField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.mechanic')),
                ('vehicle_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.insurance')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.vehicle')),
            ],
            options={
                'unique_together': {('repair_code', 'mechanic', 'vehicle', 'vehicle_insurance')},
            },
        ),
        migrations.CreateModel(
            name='Repair_has_SpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.repair')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.spareparts')),
            ],
            options={
                'unique_together': {('repair', 'spare_part')},
            },
        ),
        migrations.CreateModel(
            name='SparePart_has_Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.spareparts')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.supplier')),
            ],
            options={
                'unique_together': {('spare_part', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=45)),
                ('appointment_time', models.DateTimeField()),
                ('service_type', models.CharField(choices=[('repair', 'Repair'), ('test', 'Test')], default='repair', max_length=10)),
                ('test_completed', models.BooleanField(default=False)),
                ('repair_approved', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.invoices')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.mechanic')),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vmsms.repair')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vmsms.test')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'mechanic', 'invoice', 'appointment_id', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle_has_Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.mechanic')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'mechanic')},
            },
        ),
        migrations.CreateModel(
            name='Component_has_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.test')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.testresult')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmsms.vehiclecomponent')),
            ],
            options={
                'unique_together': {('component', 'test', 'test_result')},
            },
        ),
    ]
